# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fragmentation of Time
name: snowwhisper
email: snowwhisper.zyh@gmail.com
location: BeiJing, China
company: NCUT
company_url: http://www.ncut.edu.cn
github_url: https://github.com/snowwhisper
description: This is personnel website of snowwhisper
favicon: favicon.png # Image must be in assets/images

url: http://snowwhisper.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: snowwhisper.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++]
skill_j2ee_keywords: [Spring, Hibernet, MyBatis, JSP]
skill_web_keywords: [JQuery, Vue]
skill_mobile_app_keywords: [Android]
skill_java_web_tools: [git, maven, gradle, shell script]
